---
title: "**Comparison of Matrix Algebra Computational Performance Between Base R and RcppEigen**"
author: "**Costa Stavrianidis**"
output: pdf_document
fontsize: 10pt
indent: true
classoption:
  - twocolumn
---

```{r setup, include=FALSE}
library(tidyverse)
library(RcppEigen)
library(microbenchmark)
library(foreach)
```

\begin{center}
\textbf{\Large Abstract}
\end{center}

\begin{small}
In this study, we compare the performance of various matrix algebra computations across functions in base R and functions created using the RcppEigen package.
\end{small}

\vspace{12pt}

\begin{center}
\textbf{\Large Introduction}
\end{center}
Compiled programming languages have their programs compiled into machine-readable instructions before execution. Examples of compiled languages include C, C++, Rust, and Fortran. Interpreted languages have their programs read and executed by an interpreter rather than translating the program into machine-readable instructions. Examples of interpreted languages include Python, R, and JavaScript.

Both types of languages contain their own advantages and disadvantages. The advantage of creating a compiled program is that it is faster than an interpreted program at execution. 